### ISSUE TITLE
Pop API

### ISSUE THREAD

**Issue by javiersigler** [telefonicaid/PopBox#12]
Hello Team,

I wonder where I can find the API or what is the API to read the payloads from PopBox. 

Regards,

Javier

**Comment by mrutid** [comment]
Have you tried with the example of "Consumer" you can find at https://github.com/mrutid/PopBox/blob/unstable/examples/URLS.txt ?

You will find example JSON also in the directory.

Hope it helps.

**Comment by mrutid** [comment]
FROM:: https://github.com/mrutid/PopBox/blob/unstable/examples/URLS.txt 

# Consumer

In order to retrieve the messages  for a device, the id from the device must be append to the URL
The response is a list with the messages as strings. if there are no messages an empty list is returned ([])
By default, the consumer service listens at port 3003

Example: retrieving messages for device Ax

GET /Ax HTTP/1.1
Host: metis:3003
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:10.0.2) Gecko/20100101 Firefox/10.0.2
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: es-es,es;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 200 OK
content-type: application/json
Connection: keep-alive
Transfer-Encoding: chunked

27
["ALTA prioridad 1","baja prioridad 2"]
0

---

---

curl -v --header "Content-type: application/json" -d @Provision.json http://localhost:3000/

**Comment by javiersigler** [comment]
The content of URLS.txt is empty in the master branch. Now I see it's in the unstable branch.

**Comment by mrutid** [comment]
We are working on it... it will be in master soon (at v0.0.2). I would recomend to check unstable branch if you miss something, at least till we have the first stable version (v0.0.1 unstable)

Sorry for the confusion :) Good luck with the pop
