### ISSUE TITLE
Notification States

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/PopBox#2]

**Comment by javiersigler** [comment]
Full state diagrams of the notification states may be found in this link: https://docs.google.com/document/d/1D_5-s76kuGQdPkFWhA6uH9LYY6DKUQbWJZwVHsun_z8/edit

A brief description of the states for transactions for individual queues is the following:

OnGoing: the notification has been received and keep waiting the popper process.
Received: the notification has been successfully popped by the requesting worker.
Expired: the notification has expired.
QueueOverFlowed: the notification has been for too long in the queue has another one has popped it of the queue.
Deleted: the notification has been deleted by a deletion operation.
Erased: the historical date has expired and any trail should be erased. (Not a proper state because queries over deliveries will never return this state.

A brief description of the states for transactions for multiple queues is the following:

OnGoing: the multiple-device notification has been received.
Finished: there is not individual notification of the multiple-device notification in the OnGoing state and has not been deleted.
Deleted: the notification has been deleted.
Erased: the historical date has expired and any trail should be erased. (Not a proper state because queries over deliveries will never return this state.

Note: this solution may considered ghost elements in the queues caused by deletion, expiration or queue over flowed.

**Comment by mrutid** [comment]
We should talk about this. 

Since PopBox is transient (it must be) our preferred approach is to emit events with the different states and situations (so your own database could be subscrived and store the different historical values as long they are emited). We think this is the most generic and scalable solution.

**Comment by mrutid** [comment]
Current States:

Peding : [transactionid][queueid] - > Pushed in Box. State Event  will be emmited
Delivered:  [transactionid][queueid] -> Popped from Box. State Event  will be emmited  
Expired:  [transactionid] -> Not sent to client. No information is currently stored. State Event  will be emmited (at Pop)
